version: '3.7'
services: 
  pr2csv-test:
    container_name: pr2csv-test
    build: ../../
    volumes: 
      - pr2csv-test-data:/data
    ports: 
      - 3000:3000
    environment: 
      T_TABLE1: 'col1,col2,col3'


volumes: 
  pr2csv-test-data: